### ISSUE TITLE
Bug in quiz-questions-broken-quicklinks

### ISSUE THREAD

**Issue by danverde** [byuitechops/action-series-quiz-questions#10]
Occurred while running COMM 307 (276504)
```
message: TypeError: Cannot read property 'includes' of undefined stack: Error: TypeError: Cannot read property 'includes' of undefined
    at module.exports (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-quiz-questions\actions\quiz-questions-broken-quicklinks.js:95:22)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5317:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
    at module.exports (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-quiz-questions\actions\quiz-questions-delete.js:41:13)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5317:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
    at module.exports (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-naming-conventions.js:206:13)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
```

**Comment by sethchilders92** [comment]
Fixed this, but I'm 99% sure we aren't supposed to run this grandchild. I thought I removed it from the action series, but will do so again.
